### PR TITLE
fix edit profile button

### LINKED ISSUE #53: Edit Profile crashes app

### PR DESCRIPTION
**Pull request by ianmah**
Used VS-code auto format so a bunch of lines changed. The actual fix was in `ProfileForm.js`
Closes #53

### CODE REVIEW

File: App/components/ProfileForm.js [hunk 1]
```diff
@@ -12,11 +12,12 @@ import Button from '../components/Button'
...
-  constructor(){
-    super();
+  constructor(props) {
+    super(props);
     this.state = {
-			err: false,
-			errMessage: ''
+      err: false,
+      errMessage: '',
+      yr: props.userData.yr
```
Comment (ianmah) [inline App/components/ProfileForm.js]: changed: this line sets the state for the year

File: App/components/ProfileForm.js [hunk 2]
```diff
@@ -83,89 +84,88 @@ class Register extends Component {
...
             <Text style={{ fontSize: 10 }}>Year of Study</Text>
             <Picker
               style={styles.text}
               selectedValue={this.state.yr}
               onValueChange={(itemValue, itemIndex) => {
                 props.setFieldValue('yr', itemValue)
-                this.setState({yr: itemValue})
+                this.setState({ yr: itemValue })
               }}>
-              <Picker.Item label={this.props.userData.yr} value={this.props.userData.yr}/>
```
Comment (ianmah) [inline App/components/ProfileForm.js]: This caused a duplication of picker items which I think was causing the error. Use `selectedValue` (which is now properly set) to pick one of the actual picker items instead

File: App/components/Register.js [hunk 3]
```diff
@@ -1,4 +1,4 @@
-import React, {Component} from 'react';
```
Comment (ianmah) [inline App/components/Register.js]: this file is unchanged. Just used VS code auto format to clean it up
